Use remote env script and update checksum checking

diff --git a/hooks/post-command b/hooks/post-command
--- a/hooks/post-command
+++ b/hooks/post-command
@@ -33,14 +33,13 @@ main() {
     exit 0
   fi
 
-  curl -s https://codecov.io/bash > codecov;
+  curl -s -S --connect-timeout 10 --retry 3 --retry-delay 10 -o codecov https://codecov.io/bash;
+  curl -s -S --connect-timeout 10 --retry 3 --retry-delay 10 -o env https://codecov.io/env;
 
   CODECOV_VERSION=$(grep 'VERSION=\".*\"' codecov | cut -d'"' -f2);
-  CODECOV_SHA=$(sha1sum codecov)
-  REMOTE_SHA=$(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/$CODECOV_VERSION/SHA1SUM)
 
-  if [[ "${CODECOV_SHA}" != "${REMOTE_SHA}" ]]; then
-    echo "Codecov bash script SHA verification has failed!"
+  if ! curl -s "https://raw.githubusercontent.com/codecov/codecov-bash/${CODECOV_VERSION}/SHA1SUM" | sha1sum -c -; then
+    echo "Codecov SHA verification has failed!"
     exit 0
   fi
 
@@ -58,7 +57,7 @@ main() {
   fi
 
   local ci_env
-  ci_env=$(bash $DIR/../scripts/env)
+  ci_env=$(bash $DIR/../env)
 
   set +e
   local exit_code
